services:
- type: web
  name: apartment-reviews-app
  env: python
  repo: https://github.com/RejectsReviews/Apartment-Reviews-App.git
  plan: free
  branch: main
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn -c gunicorn_config.py 'App.main:create_app()'"
  envVars:
  - key: FLASK_APP
    value: App/main.py
  - key: ENV
    value: production
  - key: SECRET_KEY
    generateValue: true
  - key: DATABASE_URL
    fromDatabase:
      name: apartment-reviews-db
      property: connectionString
  - key: PGSSLMODE
    value: require
  - key: INIT_DATA
    value: "true"
  - key: PYTHONUNBUFFERED
    value: "true"

envVarGroups:
- name: flask-postgres-api-settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: App/main.py
    

databases:
- name: apartment-reviews-db
  plan: free
  databaseName: apartment_reviews
  ipAllowList: []  # only allow internal connections